# cat docker-compose.yml
version: '3.9'
services:
  ### MySQL Container
  mysql:
    container_name: Workout
    restart: always
    build:
      context: ..
    command:
      --default-authentication-plugin=mysql_native_password
    env_file:
      - ../.env
      #        - MYSQL_DATABASE="Workout"
    #        - MYSQL_DATABASE=${MYSQL_DATABASE}
    #        - MYSQL_USER=${MYSQL_USER}
    #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
